# Defines services, networks, and volumes for Docker containers. 
# This file includes configurations for both the Flask 
# application and Redis database.
version: '3'
services:
  # builds the Flask app using the Dockerfile
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  # pulls the Redis image specified
  redis:
    image: "redis:alpine"
